services:
  database:
    container_name: database
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
    image: app
    container_name: django-app
    env_file:
      - ./.env.production
    command: >
      sh -c "
        python manage.py collectstatic --no-input --clear &&
        python manage.py migrate &&
        gunicorn core.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - database

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/var/www/static
      - media:/var/www/media
    depends_on:
      - app

volumes:
  postgres:
  static:
  media:
